# Generated by Django 2.2.16 on 2022-02-03 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_auto_20220201_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное время приготовления = 1 минута')], verbose_name='Время приготовления в минутах'),
        ),
    ]
